### ISSUE TITLE
I want to change your icons on readme file

### ISSUE THREAD

**Issue by Its-Aman-Yadav** [Ishu-sri-001/Ishu-sri-001#1]
hey @Ishu-sri-001, I want to make your icons more attractive and cool
So, please assign me this to get started

**Comment by Ishu-sri-001** [comment]
ok... if you are requesting this much ... I guess I'll allow you.

**Comment by Its-Aman-Yadav** [comment]
Hey, @Ishu-sri-001 I have resolved the issue, please close it

**Comment by Ishu-sri-001** [comment]
Hey I review it and like the changes
Thanks
